name: "GCP Terraform Deployment"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    name: "Terraform ${{ matrix.env }}"
    runs-on: ubuntu-latest
    
    environment: ${{ matrix.env == 'prod' && 'production' || 'development' }}

    strategy:
      fail-fast: false # If Dev fails, Prod keeps running so you can see both results.
      matrix:
        env: [dev, prod]

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./environments/${{ matrix.env }}
        run: terraform init

      - name: Terraform Plan
        working-directory: ./environments/${{ matrix.env }}
        run: terraform plan -var="project_id=$GCP_PROJECT_ID"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: ./environments/${{ matrix.env }}
        run: terraform apply -auto-approve -var="project_id=$GCP_PROJECT_ID"
